// client/src/components/request-builder.tsx
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Trash2 } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import type { HttpRequest, HttpResponse } from "@/pages/api-tester";

interface RequestBuilderProps {
  request: HttpRequest;
  onRequestChange: (request: HttpRequest) => void;
  onResponse: (response: HttpResponse) => void;
  isLoading: boolean;
  setIsLoading: (loading: boolean) => void;
}

interface ParamRow {
  id: string;
  enabled: boolean;
  key: string;
  value: string;
  description: string;
}

interface HeaderRow {
  id: string;
  enabled: boolean;
  key: string;
  value: string;
  description: string;
}

export function RequestBuilder({
  request,
  onRequestChange,
  onResponse,
  isLoading,
  setIsLoading,
}: RequestBuilderProps) {
  const [activeTab, setActiveTab] = useState<"params" | "headers" | "body" | "auth">("params");
  const [params, setParams] = useState<ParamRow[]>([
    { id: "1", enabled: true, key: "", value: "", description: "" },
  ]);
  const [headers, setHeaders] = useState<HeaderRow[]>([
    { id: "1", enabled: true, key: "", value: "", description: "" },
  ]);

  const { toast } = useToast();

  const sendRequestMutation = useMutation({
    mutationFn: async () => {
      setIsLoading(true);
      
      // Build enabled params
      const enabledParams = params
        .filter((param) => param.enabled && param.key && param.value)
        .reduce((acc, param) => ({ ...acc, [param.key]: param.value }), {});

      // Build enabled headers
      const enabledHeaders = headers
        .filter((header) => header.enabled && header.key && header.value)
        .reduce((acc, header) => ({ ...acc, [header.key]: header.value }), {});

      // Build URL with params
      let finalUrl = request.url;
      const paramString = new URLSearchParams(enabledParams).toString();
      if (paramString) {
        finalUrl += (finalUrl.includes("?") ? "&" : "?") + paramString;
      }

      const response = await apiRequest("POST", "/api/proxy", {
        method: request.method,
        url: finalUrl,
        headers: enabledHeaders,
        body: request.body && request.method !== "GET" ? JSON.parse(request.body) : undefined,
      });

      return response.json();
    },
    onSuccess: (data) => {
      onResponse(data);
      setIsLoading(false);
    },
    onError: (error) => {
      toast({
        title: "Request Failed",
        description: error instanceof Error ? error.message : "Unknown error occurred",
        variant: "destructive",
      });
      setIsLoading(false);
    },
  });

  const addParamRow = () => {
    setParams([...params, { id: Date.now().toString(), enabled: true, key: "", value: "", description: "" }]);
  };

  const updateParam = (id: string, field: keyof ParamRow, value: string | boolean) => {
    setParams(params.map((param) => (param.id === id ? { ...param, [field]: value } : param)));
  };

  const removeParam = (id: string) => {
    setParams(params.filter((param) => param.id !== id));
  };

  const addHeaderRow = () => {
    setHeaders([...headers, { id: Date.now().toString(), enabled: true, key: "", value: "", description: "" }]);
  };

  const updateHeader = (id: string, field: keyof HeaderRow, value: string | boolean) => {
    setHeaders(headers.map((header) => (header.id === id ? { ...header, [field]: value } : header)));
  };

  const removeHeader = (id: string) => {
    setHeaders(headers.filter((header) => header.id !== id));
  };

  return (
    <div className="bg-white border-b border-gray-200 p-4">
      {/* Request URL Section */}
      <div className="flex items-center space-x-2 mb-4">
        <Select
          value={request.method}
          onValueChange={(value: "GET" | "POST" | "PUT" | "DELETE") =>
            onRequestChange({ ...request, method: value })
          }
        >
          <SelectTrigger className="w-32">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="GET">GET</SelectItem>
            <SelectItem value="POST">POST</SelectItem>
            <SelectItem value="PUT">PUT</SelectItem>
            <SelectItem value="DELETE">DELETE</SelectItem>
          </SelectContent>
        </Select>
        <Input
          placeholder="Enter request URL"
          value={request.url}
          onChange={(e) => onRequestChange({ ...request, url: e.target.value })}
          className="flex-1"
        />
        <Button
          onClick={() => sendRequestMutation.mutate()}
          disabled={isLoading || !request.url}
          className="bg-primary hover:bg-primary/90"
        >
          {isLoading ? "Sending..." : "Send"}
        </Button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-gray-200">
        {["params", "headers", "body", "auth"].map((tab) => (
          <button
            key={tab}
            className={`px-4 py-2 text-sm font-medium capitalize ${
              activeTab === tab
                ? "text-primary border-b-2 border-primary"
                : "text-gray-600 hover:text-gray-800"
            }`}
            onClick={() => setActiveTab(tab as any)}
          >
            {tab}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="mt-4">
        {activeTab === "params" && (
          <ParamsTable
            params={params}
            onUpdate={updateParam}
            onRemove={removeParam}
            onAdd={addParamRow}
          />
        )}

        {activeTab === "headers" && (
          <HeadersTable
            headers={headers}
            onUpdate={updateHeader}
            onRemove={removeHeader}
            onAdd={addHeaderRow}
          />
        )}

        {activeTab === "body" && (
          <div className="space-y-4">
            <Textarea
              placeholder="Request body (JSON)"
              value={request.body || ""}
              onChange={(e) => onRequestChange({ ...request, body: e.target.value })}
              className="min-h-[200px] font-mono text-sm"
            />
          </div>
        )}

        {activeTab === "auth" && (
          <div className="text-center text-gray-500 py-8">
            Authentication options coming soon
          </div>
        )}
      </div>
    </div>
  );
}

function ParamsTable({
  params,
  onUpdate,
  onRemove,
  onAdd,
}: {
  params: ParamRow[];
  onUpdate: (id: string, field: keyof ParamRow, value: string | boolean) => void;
  onRemove: (id: string) => void;
  onAdd: () => void;
}) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full">
        <thead>
          <tr className="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            <th className="w-8"></th>
            <th className="py-2 pr-4">Key</th>
            <th className="py-2 pr-4">Value</th>
            <th className="py-2 pr-4">Description</th>
            <th className="w-8"></th>
          </tr>
        </thead>
        <tbody>
          {params.map((param) => (
            <tr key={param.id} className="group">
              <td className="py-1">
                <Checkbox
                  checked={param.enabled}
                  onCheckedChange={(checked) => onUpdate(param.id, "enabled", !!checked)}
                />
              </td>
              <td className="py-1 pr-4">
                <Input
                  placeholder="Key"
                  value={param.key}
                  onChange={(e) => onUpdate(param.id, "key", e.target.value)}
                  className="text-sm"
                />
              </td>
              <td className="py-1 pr-4">
                <Input
                  placeholder="Value"
                  value={param.value}
                  onChange={(e) => onUpdate(param.id, "value", e.target.value)}
                  className="text-sm"
                />
              </td>
              <td className="py-1 pr-4">
                <Input
                  placeholder="Description"
                  value={param.description}
                  onChange={(e) => onUpdate(param.id, "description", e.target.value)}
                  className="text-sm"
                />
              </td>
              <td className="py-1">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onRemove(param.id)}
                  className="opacity-0 group-hover:opacity-100 text-gray-400 hover:text-red-500"
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <Button variant="outline" onClick={onAdd} className="mt-2">
        Add Parameter
      </Button>
    </div>
  );
}

function HeadersTable({
  headers,
  onUpdate,
  onRemove,
  onAdd,
}: {
  headers: HeaderRow[];
  onUpdate: (id: string, field: keyof HeaderRow, value: string | boolean) => void;
  onRemove: (id: string) => void;
  onAdd: () => void;
}) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full">
        <thead>
          <tr className="text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            <th className="w-8"></th>
            <th className="py-2 pr-4">Key</th>
            <th className="py-2 pr-4">Value</th>
            <th className="py-2 pr-4">Description</th>
            <th className="w-8"></th>
          </tr>
        </thead>
        <tbody>
          {headers.map((header) => (
            <tr key={header.id} className="group">
              <td className="py-1">
                <Checkbox
                  checked={header.enabled}
                  onCheckedChange={(checked) => onUpdate(header.id, "enabled", !!checked)}
                />
              </td>
              <td className="py-1 pr-4">
                <Input
                  placeholder="Key"
                  value={header.key}
                  onChange={(e) => onUpdate(header.id, "key", e.target.value)}
                  className="text-sm"
                />
              </td>
              <td className="py-1 pr-4">
                <Input
                  placeholder="Value"
                  value={header.value}
                  onChange={(e) => onUpdate(header.id, "value", e.target.value)}
                  className="text-sm"
                />
              </td>
              <td className="py-1 pr-4">
                <Input
                  placeholder="Description"
                  value={header.description}
                  onChange={(e) => onUpdate(header.id, "description", e.target.value)}
                  className="text-sm"
                />
              </td>
              <td className="py-1">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onRemove(header.id)}
                  className="opacity-0 group-hover:opacity-100 text-gray-400 hover:text-red-500"
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <Button variant="outline" onClick={onAdd} className="mt-2">
        Add Header
      </Button>
    </div>
  );
}

// client/src/app/components/request-builder/request-builder.component.ts
import { Component, Input, Output, EventEmitter, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatTabsModule } from '@angular/material/tabs';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatTableModule } from '@angular/material/table';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ApiService } from '../../services/api.service';
import type { HttpRequest, HttpResponse, ParamRow, HeaderRow } from '../../models/http-models';

@Component({
  selector: 'app-request-builder',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatTabsModule,
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatSelectModule,
    MatCheckboxModule,
    MatTableModule,
    MatSnackBarModule
  ],
  template: `
    <div class="request-builder">
      <!-- URL Bar -->
      <div class="url-bar">
        <mat-form-field appearance="outline" class="method-select">
          <mat-select [(value)]="currentRequest().method" (selectionChange)="onMethodChange($event.value)">
            <mat-option value="GET">GET</mat-option>
            <mat-option value="POST">POST</mat-option>
            <mat-option value="PUT">PUT</mat-option>
            <mat-option value="DELETE">DELETE</mat-option>
          </mat-select>
        </mat-form-field>
        
        <mat-form-field appearance="outline" class="url-input">
          <input matInput placeholder="Enter request URL" 
                 [(ngModel)]="currentRequest().url"
                 (ngModelChange)="onUrlChange($event)">
        </mat-form-field>
        
        <button mat-raised-button color="primary" 
                [disabled]="isLoading || !currentRequest().url"
                (click)="sendRequest()"
                class="send-button">
          {{ isLoading ? 'Sending...' : 'Send' }}
        </button>
      </div>

      <!-- Tabs -->
      <mat-tab-group class="request-tabs">
        <mat-tab label="Params">
          <div class="tab-content">
            <div class="params-table">
              <div class="table-header">
                <div class="header-cell">Enabled</div>
                <div class="header-cell">Key</div>
                <div class="header-cell">Value</div>
                <div class="header-cell">Description</div>
                <div class="header-cell">Actions</div>
              </div>
              
              <div *ngFor="let param of params(); let i = index" class="table-row">
                <div class="cell">
                  <mat-checkbox [(ngModel)]="param.enabled" (change)="updateParam(i, 'enabled', $event.checked)">
                  </mat-checkbox>
                </div>
                <div class="cell">
                  <mat-form-field appearance="outline">
                    <input matInput placeholder="Key" 
                           [(ngModel)]="param.key"
                           (ngModelChange)="updateParam(i, 'key', $event)">
                  </mat-form-field>
                </div>
                <div class="cell">
                  <mat-form-field appearance="outline">
                    <input matInput placeholder="Value" 
                           [(ngModel)]="param.value"
                           (ngModelChange)="updateParam(i, 'value', $event)">
                  </mat-form-field>
                </div>
                <div class="cell">
                  <mat-form-field appearance="outline">
                    <input matInput placeholder="Description" 
                           [(ngModel)]="param.description"
                           (ngModelChange)="updateParam(i, 'description', $event)">
                  </mat-form-field>
                </div>
                <div class="cell">
                  <button mat-icon-button color="warn" (click)="removeParam(i)">
                    <mat-icon>delete</mat-icon>
                  </button>
                </div>
              </div>
              
              <button mat-button color="primary" (click)="addParam()" class="add-button">
                <mat-icon>add</mat-icon>
                Add Parameter
              </button>
            </div>
          </div>
        </mat-tab>

        <mat-tab label="Headers">
          <div class="tab-content">
            <div class="headers-table">
              <div class="table-header">
                <div class="header-cell">Enabled</div>
                <div class="header-cell">Key</div>
                <div class="header-cell">Value</div>
                <div class="header-cell">Description</div>
                <div class="header-cell">Actions</div>
              </div>
              
              <div *ngFor="let header of headers(); let i = index" class="table-row">
                <div class="cell">
                  <mat-checkbox [(ngModel)]="header.enabled" (change)="updateHeader(i, 'enabled', $event.checked)">
                  </mat-checkbox>
                </div>
                <div class="cell">
                  <mat-form-field appearance="outline">
                    <input matInput placeholder="Key" 
                           [(ngModel)]="header.key"
                           (ngModelChange)="updateHeader(i, 'key', $event)">
                  </mat-form-field>
                </div>
                <div class="cell">
                  <mat-form-field appearance="outline">
                    <input matInput placeholder="Value" 
                           [(ngModel)]="header.value"
                           (ngModelChange)="updateHeader(i, 'value', $event)">
                  </mat-form-field>
                </div>
                <div class="cell">
                  <mat-form-field appearance="outline">
                    <input matInput placeholder="Description" 
                           [(ngModel)]="header.description"
                           (ngModelChange)="updateHeader(i, 'description', $event)">
                  </mat-form-field>
                </div>
                <div class="cell">
                  <button mat-icon-button color="warn" (click)="removeHeader(i)">
                    <mat-icon>delete</mat-icon>
                  </button>
                </div>
              </div>
              
              <button mat-button color="primary" (click)="addHeader()" class="add-button">
                <mat-icon>add</mat-icon>
                Add Header
              </button>
            </div>
          </div>
        </mat-tab>

        <mat-tab label="Body">
          <div class="tab-content">
            <mat-form-field appearance="outline" class="body-field">
              <textarea matInput placeholder="Request body (JSON)" 
                        rows="15"
                        [(ngModel)]="currentRequest().body"
                        (ngModelChange)="onBodyChange($event)">
              </textarea>
            </mat-form-field>
          </div>
        </mat-tab>

        <mat-tab label="Auth">
          <div class="tab-content">
            <div class="auth-placeholder">
              <mat-icon>lock</mat-icon>
              <p>Authentication options coming soon</p>
            </div>
          </div>
        </mat-tab>
      </mat-tab-group>
    </div>
  `,
  styles: [`
    .request-builder {
      background: white;
      border-bottom: 1px solid #e0e0e0;
    }

    .url-bar {
      display: flex;
      gap: 12px;
      padding: 16px;
      align-items: center;
      border-bottom: 1px solid #f0f0f0;
    }

    .method-select {
      width: 120px;
    }

    .url-input {
      flex: 1;
    }

    .send-button {
      height: 56px;
      padding: 0 24px;
    }

    .request-tabs {
      min-height: 400px;
    }

    .tab-content {
      padding: 16px;
    }

    .params-table, .headers-table {
      width: 100%;
    }

    .table-header {
      display: grid;
      grid-template-columns: 80px 1fr 1fr 1fr 80px;
      gap: 12px;
      padding: 8px 0;
      border-bottom: 1px solid #e0e0e0;
      font-weight: 500;
      color: #666;
    }

    .table-row {
      display: grid;
      grid-template-columns: 80px 1fr 1fr 1fr 80px;
      gap: 12px;
      padding: 8px 0;
      align-items: center;
    }

    .header-cell {
      font-size: 12px;
      text-transform: uppercase;
    }

    .cell {
      display: flex;
      align-items: center;
    }

    .cell mat-form-field {
      width: 100%;
    }

    .add-button {
      margin-top: 16px;
    }

    .body-field {
      width: 100%;
    }

    .body-field textarea {
      font-family: 'Courier New', monospace;
      font-size: 14px;
    }

    .auth-placeholder {
      text-align: center;
      padding: 48px 16px;
      color: #666;
    }

    .auth-placeholder mat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
      margin-bottom: 16px;
      opacity: 0.5;
    }
  `]
})
export class RequestBuilderComponent implements OnInit {
  @Input() request!: HttpRequest;
  @Input() isLoading = false;
  @Output() requestChange = new EventEmitter<HttpRequest>();
  @Output() sendRequestEvent = new EventEmitter<any>();

  params = signal<ParamRow[]>([
    { id: '1', enabled: true, key: '', value: '', description: '' }
  ]);

  headers = signal<HeaderRow[]>([
    { id: '1', enabled: true, key: '', value: '', description: '' }
  ]);

  constructor(
    private apiService: ApiService,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit() {
    // Initialize with the input request
  }

  currentRequest = signal<HttpRequest>({
    method: 'GET',
    url: '',
    headers: {},
    params: {},
    body: ''
  });

  onMethodChange(method: string) {
    const updated = { ...this.currentRequest(), method: method as any };
    this.currentRequest.set(updated);
    this.requestChange.emit(updated);
  }

  onUrlChange(url: string) {
    const updated = { ...this.currentRequest(), url };
    this.currentRequest.set(updated);
    this.requestChange.emit(updated);
  }

  onBodyChange(body: string) {
    const updated = { ...this.currentRequest(), body };
    this.currentRequest.set(updated);
    this.requestChange.emit(updated);
  }

  // Params methods
  addParam() {
    this.params.update(current => [
      ...current,
      { id: Date.now().toString(), enabled: true, key: '', value: '', description: '' }
    ]);
  }

  updateParam(index: number, field: keyof ParamRow, value: any) {
    this.params.update(current => {
      const updated = [...current];
      updated[index] = { ...updated[index], [field]: value };
      return updated;
    });
  }

  removeParam(index: number) {
    this.params.update(current => current.filter((_, i) => i !== index));
  }

  // Headers methods
  addHeader() {
    this.headers.update(current => [
      ...current,
      { id: Date.now().toString(), enabled: true, key: '', value: '', description: '' }
    ]);
  }

  updateHeader(index: number, field: keyof HeaderRow, value: any) {
    this.headers.update(current => {
      const updated = [...current];
      updated[index] = { ...updated[index], [field]: value };
      return updated;
    });
  }

  removeHeader(index: number) {
    this.headers.update(current => current.filter((_, i) => i !== index));
  }

  sendRequest() {
    const enabledParams = this.params()
      .filter(p => p.enabled && p.key && p.value)
      .reduce((acc, p) => ({ ...acc, [p.key]: p.value }), {});

    const enabledHeaders = this.headers()
      .filter(h => h.enabled && h.key && h.value)
      .reduce((acc, h) => ({ ...acc, [h.key]: h.value }), {});

    let finalUrl = this.currentRequest().url;
    const paramString = new URLSearchParams(enabledParams).toString();
    if (paramString) {
      finalUrl += (finalUrl.includes('?') ? '&' : '?') + paramString;
    }

    const requestData = {
      method: this.currentRequest().method,
      url: finalUrl,
      headers: enabledHeaders,
      body: this.currentRequest().body && this.currentRequest().method !== 'GET' 
        ? JSON.parse(this.currentRequest().body || '{}') 
        : undefined
    };

    this.apiService.sendRequest(requestData).subscribe({
      next: (response) => {
        this.sendRequestEvent.emit(response);
        this.snackBar.open('Request sent successfully', 'Close', { duration: 3000 });
      },
      error: (error) => {
        this.snackBar.open('Request failed: ' + error.message, 'Close', { duration: 5000 });
      }
    });
  }
}
