// client/src/app/components/response-viewer/response-viewer.component.ts
import { Component, Input, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTabsModule } from '@angular/material/tabs';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import { HttpResponse } from '../../models/http-models';

@Component({
  selector: 'app-response-viewer',
  standalone: true,
  imports: [
    CommonModule,
    MatTabsModule,
    MatButtonModule,
    MatIconModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatSnackBarModule
  ],
  template: `
    <div class="response-viewer">
      <div class="response-header" *ngIf="response">
        <div class="response-info">
          <h3 class="response-title">Response</h3>
          <div class="response-meta">
            <mat-chip-set>
              <mat-chip [ngClass]="getStatusClass(response.status)">
                {{ response.status }} {{ response.statusText }}
              </mat-chip>
              <mat-chip>Time: {{ response.time }}</mat-chip>
              <mat-chip>Size: {{ response.size }}</mat-chip>
            </mat-chip-set>
          </div>
        </div>
        <div class="response-actions">
          <button mat-button (click)="copyResponse()">
            <mat-icon>content_copy</mat-icon>
            Copy
          </button>
          <button mat-button>
            <mat-icon>save</mat-icon>
            Save
          </button>
        </div>
      </div>

      <div class="response-content" *ngIf="response && !isLoading; else loadingOrEmpty">
        <mat-tab-group class="response-tabs">
          <mat-tab label="Body">
            <div class="tab-content">
              <div class="view-mode-buttons">
                <button mat-button 
                        [class.active]="viewMode() === 'pretty'"
                        (click)="viewMode.set('pretty')">
                  Pretty
                </button>
                <button mat-button 
                        [class.active]="viewMode() === 'raw'"
                        (click)="viewMode.set('raw')">
                  Raw
                </button>
                <button mat-button 
                        [class.active]="viewMode() === 'preview'"
                        (click)="viewMode.set('preview')">
                  Preview
                </button>
              </div>
              
              <div class="response-body">
                <div *ngIf="viewMode() === 'pretty' && isJsonResponse()" class="json-viewer" [innerHTML]="getFormattedJson()">
                </div>
                <pre *ngIf="viewMode() === 'raw' || !isJsonResponse()" class="raw-viewer">{{ getResponseText() }}</pre>
                <div *ngIf="viewMode() === 'preview'" class="preview-viewer">
                  <p>Preview mode - showing formatted content</p>
                  <pre>{{ getResponseText() }}</pre>
                </div>
              </div>
            </div>
          </mat-tab>

          <mat-tab label="Headers">
            <div class="tab-content">
              <div class="headers-table">
                <div *ngFor="let header of getHeaderEntries()" class="header-row">
                  <div class="header-key">{{ header.key }}:</div>
                  <div class="header-value">{{ header.value }}</div>
                </div>
              </div>
            </div>
          </mat-tab>

          <mat-tab label="Test Results">
            <div class="tab-content">
              <div class="test-placeholder">
                <mat-icon>check_circle</mat-icon>
                <p>Test results will appear here</p>
                <p class="subtitle">Write tests to validate your API responses</p>
              </div>
            </div>
          </mat-tab>
        </mat-tab-group>
      </div>

      <ng-template #loadingOrEmpty>
        <div class="empty-state" *ngIf="!isLoading">
          <mat-icon>http</mat-icon>
          <h3>No Response</h3>
          <p>Send a request to see the response here</p>
        </div>
        
        <div class="loading-state" *ngIf="isLoading">
          <mat-spinner diameter="40"></mat-spinner>
          <p>Waiting for response...</p>
        </div>
      </ng-template>
    </div>
  `,
  styles: [`
    .response-viewer {
      flex: 1;
      background: white;
      display: flex;
      flex-direction: column;
      overflow: hidden;
    }

    .response-header {
      padding: 16px;
      border-bottom: 1px solid #e0e0e0;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .response-title {
      margin: 0 0 8px 0;
      font-size: 18px;
      font-weight: 500;
    }

    .response-meta mat-chip-set {
      display: flex;
      gap: 8px;
    }

    .response-actions {
      display: flex;
      gap: 8px;
    }

    .response-content {
      flex: 1;
      overflow: hidden;
    }

    .response-tabs {
      height: 100%;
    }

    .tab-content {
      padding: 16px;
      height: calc(100% - 48px);
      overflow: auto;
    }

    .view-mode-buttons {
      display: flex;
      gap: 8px;
      margin-bottom: 16px;
      border-bottom: 1px solid #e0e0e0;
      padding-bottom: 8px;
    }

    .view-mode-buttons button.active {
      background-color: #e3f2fd;
      color: #1976d2;
    }

    .response-body {
      height: calc(100% - 60px);
      overflow: auto;
    }

    .json-viewer {
      font-family: 'Courier New', monospace;
      background: #f8f9fa;
      border-radius: 8px;
      padding: 16px;
      font-size: 14px;
      line-height: 1.5;
      white-space: pre-wrap;
      overflow-x: auto;
    }

    .raw-viewer {
      font-family: 'Courier New', monospace;
      background: #f8f9fa;
      border-radius: 8px;
      padding: 16px;
      font-size: 14px;
      line-height: 1.5;
      white-space: pre-wrap;
      overflow-x: auto;
      margin: 0;
    }

    .preview-viewer {
      background: #f8f9fa;
      border-radius: 8px;
      padding: 16px;
    }

    .headers-table {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .header-row {
      display: flex;
      padding: 8px 0;
      border-bottom: 1px solid #f0f0f0;
    }

    .header-key {
      width: 200px;
      font-weight: 500;
      color: #666;
    }

    .header-value {
      flex: 1;
      word-break: break-all;
    }

    .empty-state, .loading-state {
      flex: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 48px;
      color: #666;
      text-align: center;
    }

    .empty-state mat-icon, .loading-state mat-icon {
      font-size: 64px;
      width: 64px;
      height: 64px;
      margin-bottom: 16px;
      opacity: 0.5;
    }

    .loading-state {
      gap: 16px;
    }

    .test-placeholder {
      text-align: center;
      padding: 48px 16px;
      color: #666;
    }

    .test-placeholder mat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
      margin-bottom: 16px;
      opacity: 0.5;
    }

    .subtitle {
      font-size: 14px;
      color: #999;
      margin: 8px 0 0 0;
    }

    /* Status chip styles */
    .status-success {
      background-color: #e8f5e8 !important;
      color: #2e7d32 !important;
    }

    .status-error {
      background-color: #ffebee !important;
      color: #c62828 !important;
    }

    .status-warning {
      background-color: #fff3e0 !important;
      color: #ef6c00 !important;
    }
  `]
})
export class ResponseViewerComponent {
  @Input() response: HttpResponse | null = null;
  @Input() isLoading = false;

  viewMode = signal<'pretty' | 'raw' | 'preview'>('pretty');

  constructor() {}

  getStatusClass(status: number): string {
    if (status >= 200 && status < 300) return 'status-success';
    if (status >= 400 && status < 500) return 'status-error';
    if (status >= 500) return 'status-error';
    return 'status-warning';
  }

  isJsonResponse(): boolean {
    if (!this.response) return false;
    return typeof this.response.body === 'object';
  }

  getResponseText(): string {
    if (!this.response) return '';
    return typeof this.response.body === 'string' 
      ? this.response.body 
      : JSON.stringify(this.response.body, null, 2);
  }

  getFormattedJson(): string {
    if (!this.response || !this.isJsonResponse()) return '';
    
    const jsonString = JSON.stringify(this.response.body, null, 2);
    
    // Simple syntax highlighting
    return jsonString
      .replace(/"([^"]+)":/g, '<span class="json-key">"$1"</span>:')
      .replace(/: "([^"]+)"/g, ': <span class="json-string">"$1"</span>')
      .replace(/: (\d+\.?\d*)/g, ': <span class="json-number">$1</span>')
      .replace(/: (true|false)/g, ': <span class="json-boolean">$1</span>')
      .replace(/: (null)/g, ': <span class="json-null">$1</span>');
  }

  getHeaderEntries(): { key: string; value: string }[] {
    if (!this.response) return [];
    return Object.entries(this.response.headers).map(([key, value]) => ({ key, value }));
  }

  async copyResponse() {
    if (!this.response) return;
    
    try {
      const text = this.getResponseText();
      await navigator.clipboard.writeText(text);
      console.log('Response copied to clipboard');
    } catch (error) {
      console.error('Failed to copy to clipboard');
    }
  }
}

// client/src/components/response-viewer.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { SyntaxHighlighter } from "@/components/syntax-highlighter";
import { Copy, Save } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import type { HttpResponse } from "@/pages/api-tester";

interface ResponseViewerProps {
  response: HttpResponse | null;
}

export function ResponseViewer({ response }: ResponseViewerProps) {
  const [activeTab, setActiveTab] = useState<"body" | "headers" | "test">("body");
  const [viewMode, setViewMode] = useState<"pretty" | "raw" | "preview">("pretty");
  const { toast } = useToast();

  const getStatusColor = (status: number) => {
    if (status >= 200 && status < 300) return "status-success";
    if (status >= 400 && status < 500) return "status-error";
    if (status >= 500) return "status-error";
    return "status-warning";
  };

  const copyToClipboard = async () => {
    if (!response) return;
    
    try {
      const text = typeof response.body === "string" 
        ? response.body 
        : JSON.stringify(response.body, null, 2);
      await navigator.clipboard.writeText(text);
      toast({
        title: "Copied",
        description: "Response copied to clipboard",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard",
        variant: "destructive",
      });
    }
  };

  if (!response) {
    return (
      <div className="flex-1 bg-white flex items-center justify-center">
        <div className="text-center text-gray-500">
          <div className="text-lg font-medium mb-2">No Response</div>
          <div className="text-sm">Send a request to see the response here</div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 bg-white overflow-hidden">
      {/* Response Header */}
      <div className="p-4 border-b border-gray-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <h3 className="text-lg font-medium text-gray-800">Response</h3>
            <div className="flex items-center space-x-2">
              <Badge className={`${getStatusColor(response.status)} bg-opacity-10 border-0`}>
                {response.status} {response.statusText}
              </Badge>
              <span className="text-sm text-gray-600">
                Time: <span className="font-medium">{response.time}</span>
              </span>
              <span className="text-sm text-gray-600">
                Size: <span className="font-medium">{response.size}</span>
              </span>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <Button variant="outline" size="sm" onClick={copyToClipboard}>
              <Copy className="w-4 h-4 mr-2" />
              Copy
            </Button>
            <Button variant="outline" size="sm">
              <Save className="w-4 h-4 mr-2" />
              Save
            </Button>
          </div>
        </div>
      </div>

      {/* Response Tabs */}
      <div className="flex border-b border-gray-200 px-4">
        {["body", "headers", "test"].map((tab) => (
          <button
            key={tab}
            className={`px-4 py-2 text-sm font-medium capitalize ${
              activeTab === tab
                ? "text-primary border-b-2 border-primary"
                : "text-gray-600 hover:text-gray-800"
            }`}
            onClick={() => setActiveTab(tab as any)}
          >
            {tab === "test" ? "Test Results" : tab}
          </button>
        ))}
      </div>

      {/* Response Content */}
      <div className="flex-1 overflow-auto p-4">
        {activeTab === "body" && (
          <>
            <div className="flex justify-between items-center mb-4">
              <div className="flex items-center space-x-2">
                {["pretty", "raw", "preview"].map((mode) => (
                  <button
                    key={mode}
                    className={`px-3 py-1 text-xs font-medium rounded capitalize ${
                      viewMode === mode
                        ? "bg-gray-100 text-gray-600"
                        : "text-gray-600 hover:bg-gray-100"
                    }`}
                    onClick={() => setViewMode(mode as any)}
                  >
                    {mode}
                  </button>
                ))}
              </div>
              <span className="text-xs text-gray-500">
                {typeof response.body === "object" ? "JSON" : "Text"}
              </span>
            </div>

            {viewMode === "pretty" && typeof response.body === "object" ? (
              <SyntaxHighlighter
                code={JSON.stringify(response.body, null, 2)}
                language="json"
              />
            ) : (
              <div className="syntax-highlight overflow-auto">
                <pre className="text-sm whitespace-pre-wrap">
                  {typeof response.body === "string"
                    ? response.body
                    : JSON.stringify(response.body, null, 2)}
                </pre>
              </div>
            )}
          </>
        )}

        {activeTab === "headers" && (
          <div className="space-y-2">
            {Object.entries(response.headers).map(([key, value]) => (
              <div key={key} className="flex">
                <div className="w-1/3 text-sm font-medium text-gray-600 pr-4">{key}:</div>
                <div className="flex-1 text-sm text-gray-800">{value}</div>
              </div>
            ))}
          </div>
        )}

        {activeTab === "test" && (
          <div className="text-center text-gray-500 py-8">
            Test results will appear here
          </div>
        )}
      </div>
    </div>
  );
}
